export const seedProducts = [
  {
    name: "Royal Kanjivaram Silk Saree",
    slug: "royal-kanjivaram-silk-saree",
    category: "Silk Sarees",
    fabric: "Silk Blend",
    occasion: "Wedding",
    color: "Purple",
    price: 12499,
    originalPrice: 15000,
    image: "/images/product1.jpg",
    images: ["/images/product1.jpg", "/images/silk.jpg", "/images/festive.jpg"],
    stock: 7,
    tag: "Bestseller",
    collections: ["kanjivaram", "bridal", "party-wear", "traditional", "south-indian"],
    description: "A festive silk saree with jewel tones and rich borders, made for weddings and family celebrations.",
    details: ["Silk blend fabric", "Zari inspired border", "Blouse piece included", "Dry clean recommended"],
  },
  {
    name: "Banarasi Brocade Wedding Saree",
    slug: "banarasi-brocade-wedding-saree",
    category: "Wedding Collection",
    fabric: "Brocade",
    occasion: "Wedding",
    color: "Red",
    price: 9999,
    originalPrice: 13000,
    image: "/images/wedding.jpg",
    images: ["/images/wedding.jpg", "/images/festive.jpg", "/images/product1.jpg"],
    stock: 0,
    tag: "Sold Out",
    collections: ["banarasi", "bridal", "traditional", "red", "heirloom"],
    description: "A statement red brocade saree styled for bridal events, receptions, and ceremonial occasions.",
    details: ["Brocade weave", "Rich red tone", "Blouse piece included", "No return or exchange"],
  },
  {
    name: "Chanderi Cotton Day Saree",
    slug: "chanderi-cotton-day-saree",
    category: "Cotton Sarees",
    fabric: "Cotton",
    occasion: "Daily Wear",
    color: "Magenta",
    price: 4299,
    originalPrice: 5000,
    image: "/images/cotton.jpg",
    images: ["/images/cotton.jpg", "/images/hero-heritage.png", "/images/hero-elegance.png"],
    stock: 0,
    tag: "Sold Out",
    collections: ["summer", "daily-wear", "chanderi", "casual", "pink"],
    description: "A lightweight cotton saree for elegant day wear, summer occasions, and intimate gatherings.",
    details: ["Soft cotton feel", "Lightweight drape", "Easy day styling", "Dry in shade"],
  },
  {
    name: "Patola Inspired Festive Saree",
    slug: "patola-inspired-festive-saree",
    category: "Festive Wear",
    fabric: "Silk Cotton",
    occasion: "Festive",
    color: "Green",
    price: 18999,
    originalPrice: 24000,
    image: "/images/festive.jpg",
    images: ["/images/festive.jpg", "/images/hero-elegance.png", "/images/silk.jpg"],
    stock: 4,
    tag: "Limited",
    collections: ["party-wear", "traditional", "silk-cotton", "patola", "gujarati"],
    description: "A festive saree with traditional color blocking and an elevated silk-cotton finish.",
    details: ["Silk cotton fabric", "Festive zari accents", "Blouse piece included", "Dry clean only"],
  },
  {
    name: "Heritage Floral Saree",
    slug: "heritage-floral-saree",
    category: "New Arrivals",
    fabric: "Organza Blend",
    occasion: "Celebration",
    color: "Ivory",
    price: 7499,
    originalPrice: 8999,
    image: "/images/hero-heritage.png",
    images: ["/images/hero-heritage.png", "/images/hero-elegance.png", "/images/cotton.jpg"],
    stock: 9,
    tag: "New",
    collections: ["summer", "party-wear", "designer", "floral", "pastel"],
    description: "A graceful floral saree with soft tones, designed for warm-weather functions and refined gifting.",
    details: ["Organza blend", "Soft floral print", "Light festive feel", "Blouse piece included"],
  },
  {
    name: "Bridal Red Luxury Saree",
    slug: "bridal-red-luxury-saree",
    category: "Wedding Collection",
    fabric: "Embroidered Silk",
    occasion: "Bridal",
    color: "Red",
    price: 25999,
    originalPrice: 31500,
    image: "/images/hero-bridal.png",
    images: ["/images/hero-bridal.png", "/images/wedding.jpg", "/images/product1.jpg"],
    stock: 3,
    tag: "Premium",
    collections: ["bridal", "party-wear", "traditional", "embroidery", "wedding"],
    description: "A regal bridal saree with ornate detailing, created for wedding ceremonies and heirloom styling.",
    details: ["Embroidered silk", "Bridal finish", "Premium zari work", "Dry clean only"],
  },
  {
    name: "Pastel Garden Silk Cotton Saree",
    slug: "pastel-garden-silk-cotton-saree",
    category: "New Arrivals",
    fabric: "Silk Cotton",
    occasion: "Summer Celebration",
    color: "Pastel",
    price: 5999,
    originalPrice: 7499,
    image: "/images/hero-heritage.png",
    images: ["/images/hero-heritage.png", "/images/cotton.jpg", "/images/hero-elegance.png"],
    stock: 8,
    tag: "New Arrivals",
    collections: ["summer", "pastel", "floral", "printed", "party-wear"],
    description: "A soft pastel saree with a graceful festive mood, perfect for brunches, gifting, and day celebrations.",
    details: ["Silk cotton blend", "Pastel floral look", "Comfortable drape", "Blouse piece included"],
  },
  {
    name: "Teal Banarasi Silk Saree",
    slug: "teal-banarasi-silk-saree",
    category: "Silk Sarees",
    fabric: "Banarasi Silk",
    occasion: "Engagement",
    color: "Blue",
    price: 15499,
    originalPrice: 18999,
    image: "/images/hero-elegance.png",
    images: ["/images/hero-elegance.png", "/images/silk.jpg", "/images/hero-bridal.png"],
    stock: 5,
    tag: "New Arrivals",
    collections: ["blue", "banarasi", "heirloom", "engagement", "wedding"],
    description: "A refined teal silk saree with a ceremonial finish and a calm, premium presence.",
    details: ["Banarasi inspired weave", "Teal blue tone", "Occasion-ready border", "Dry clean only"],
  },
  {
    name: "Ivory Rose Organza Saree",
    slug: "ivory-rose-organza-saree",
    category: "Festive Wear",
    fabric: "Organza",
    occasion: "Reception",
    color: "Ivory",
    price: 8999,
    originalPrice: 10500,
    image: "/images/hero-elegance.png",
    images: ["/images/hero-elegance.png", "/images/hero-heritage.png", "/images/cotton.jpg"],
    stock: 6,
    tag: "Limited",
    collections: ["ivory", "pastel", "floral", "reception", "designer"],
    description: "A polished ivory saree with a soft rose border, made for elegant evening occasions.",
    details: ["Organza finish", "Soft rose border", "Light shimmer", "Blouse piece included"],
  },
  {
    name: "Mustard Haldi Tissue Saree",
    slug: "mustard-haldi-tissue-saree",
    category: "Festive Wear",
    fabric: "Tissue",
    occasion: "Haldi",
    color: "Yellow",
    price: 6999,
    originalPrice: 8500,
    image: "/images/silk.jpg",
    images: ["/images/silk.jpg", "/images/festive.jpg", "/images/hero-heritage.png"],
    stock: 10,
    tag: "Festive",
    collections: ["yellow", "haldi", "tissue", "festive", "summer-wedding"],
    description: "A bright yet elegant tissue saree selected for haldi mornings and festive family rituals.",
    details: ["Tissue blend", "Light festive sheen", "Haldi friendly palette", "Blouse piece included"],
  },
  {
    name: "Black Evening Crepe Saree",
    slug: "black-evening-crepe-saree",
    category: "New Arrivals",
    fabric: "Crepe",
    occasion: "Party Wear",
    color: "Black",
    price: 5499,
    originalPrice: 7000,
    image: "/images/product1.jpg",
    images: ["/images/product1.jpg", "/images/wedding.jpg", "/images/festive.jpg"],
    stock: 0,
    tag: "Sold Out",
    collections: ["black", "party-wear", "crepe", "evening", "plain"],
    description: "A minimal evening saree with clean movement, made for polished party styling.",
    details: ["Crepe fabric", "Evening-ready drape", "Minimal border", "No return or exchange"],
  },
  {
    name: "Peach Linen Casual Saree",
    slug: "peach-linen-casual-saree",
    category: "Cotton Sarees",
    fabric: "Linen Cotton",
    occasion: "Casual",
    color: "Peach",
    price: 3499,
    originalPrice: 4500,
    image: "/images/cotton.jpg",
    images: ["/images/cotton.jpg", "/images/hero-heritage.png", "/images/silk.jpg"],
    stock: 12,
    tag: "Online Exclusive",
    collections: ["peach", "linen", "casual", "daily-wear", "summer"],
    description: "A breathable peach linen-cotton saree for workdays, lunches, and relaxed celebrations.",
    details: ["Linen cotton fabric", "Breathable feel", "Soft peach tone", "Easy drape"],
  },
  {
    name: "Blue Embroidered Dress Material Set",
    slug: "blue-embroidered-dress-material-set",
    category: "Dress Materials",
    fabric: "Georgette Blend",
    occasion: "Festive",
    color: "Blue",
    price: 2499,
    originalPrice: 3299,
    image: "/images/dress-materials-blue.jpg",
    images: ["/images/dress-materials-blue.jpg", "/images/dress-materials-blue.jpg", "/images/dress-materials-blue.jpg"],
    stock: 14,
    tag: "New",
    collections: ["dress-material", "blue", "embroidered", "festive", "georgette"],
    description: "A blue unstitched dress material set with embroidered neckline work, matching bottom fabric, and dupatta.",
    details: ["Unstitched kurta fabric", "Matching bottom fabric", "Printed dupatta included", "Embroidery neckline detail"],
  },
  {
    name: "Navy Floral Dress Material Set",
    slug: "navy-floral-dress-material-set",
    category: "Dress Materials",
    fabric: "Cotton Blend",
    occasion: "Daily Wear",
    color: "Navy",
    price: 1799,
    originalPrice: 2299,
    image: "/images/dress-materials-blue.jpg",
    images: ["/images/dress-materials-blue.jpg", "/images/dress-materials-blue.jpg", "/images/dress-materials-blue.jpg"],
    stock: 6,
    tag: "Limited",
    collections: ["dress-material", "cotton", "daily-wear", "navy", "printed"],
    description: "A soft printed dress material set for comfortable tailoring and everyday ethnic styling.",
    details: ["Unstitched set", "Cotton blend fabric", "Printed dupatta", "Comfortable daily wear"],
  },
  {
    name: "Party Wear Embroidered Suit Material",
    slug: "party-wear-embroidered-suit-material",
    category: "Dress Materials",
    fabric: "Silk Blend",
    occasion: "Party Wear",
    color: "Blue",
    price: 3499,
    originalPrice: 4499,
    image: "/images/dress-materials-blue.jpg",
    images: ["/images/dress-materials-blue.jpg", "/images/dress-materials-blue.jpg", "/images/dress-materials-blue.jpg"],
    stock: 9,
    tag: "New Arrivals",
    collections: ["dress-material", "blue", "party-wear", "silk", "embroidered"],
    description: "A polished embroidered suit material set for festive evenings, family functions, and parties.",
    details: ["Unstitched suit material", "Embroidered front panel", "Dupatta included", "Dry clean recommended"],
  },
  {
    name: "Premium Blue Occasion Dress Material",
    slug: "premium-blue-occasion-dress-material",
    category: "Dress Materials",
    fabric: "Organza Blend",
    occasion: "Wedding",
    color: "Blue",
    price: 5499,
    originalPrice: 6500,
    image: "/images/dress-materials-blue.jpg",
    images: ["/images/dress-materials-blue.jpg", "/images/dress-materials-blue.jpg", "/images/dress-materials-blue.jpg"],
    stock: 4,
    tag: "Premium",
    collections: ["dress-material", "wedding", "blue", "organza", "premium"],
    description: "A premium blue dress material set selected for wedding events, receptions, and graceful family functions.",
    details: ["Premium unstitched set", "Occasion-ready fabric", "Dupatta included", "No return or exchange"],
  },
  {
    name: "Blue Printed Dupatta Dress Material",
    slug: "blue-printed-dupatta-dress-material",
    category: "Dress Materials",
    fabric: "Chiffon Blend",
    occasion: "Casual",
    color: "Blue",
    price: 2199,
    originalPrice: 3000,
    image: "/images/dress-materials-blue.jpg",
    images: ["/images/dress-materials-blue.jpg", "/images/dress-materials-blue.jpg", "/images/dress-materials-blue.jpg"],
    stock: 11,
    tag: "Online Exclusive",
    collections: ["dress-material", "casual", "blue", "chiffon", "printed"],
    description: "An easy-to-tailor dress material set with a soft printed dupatta and coordinated bottom fabric.",
    details: ["Unstitched dress material", "Printed dupatta", "Coordinated bottom", "Gentle wash recommended"],
  },
  {
    name: "Designer Neck Work Dress Material",
    slug: "designer-neck-work-dress-material",
    category: "Dress Materials",
    fabric: "Rayon Blend",
    occasion: "Festive",
    color: "Blue",
    price: 2899,
    originalPrice: 3599,
    image: "/images/dress-materials-blue.jpg",
    images: ["/images/dress-materials-blue.jpg", "/images/dress-materials-blue.jpg", "/images/dress-materials-blue.jpg"],
    stock: 0,
    tag: "Sold Out",
    collections: ["dress-material", "designer", "embroidered", "festive", "rayon"],
    description: "A designer dress material set with decorative neckline work and a coordinated printed dupatta.",
    details: ["Designer neck detail", "Unstitched fabric", "Dupatta included", "No return or exchange"],
  },
];
